services:
  - type: web
    name: hearing-clinic
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    customDomains:
      - hearingclinicislamabad.com
      - www.hearingclinicislamabad.com
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: hearing-clinic-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://hearingclinicislamabad.com